server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hw30_schema
    username: root
    password: MySQL_Nikolenko_12
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.web: INFO
    com.yourpackage: INFO
  file:
    name: logs/app.log
